name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release
